apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: uniapp

resources:
  - ../../api/deployment.yaml
  - ../../api/service.yaml
  - ../../web/deployment.yaml
  - ../../web/service.yaml
  - ../../base/namespace.yaml
  - ../../base/hpa.yaml
  - ../../base/secrets.yaml

images:
  - name: uniapp/api
    newName: ghcr.io/dillon-co/uniapp-api
    newTag: latest
  - name: uniapp/web
    newName: ghcr.io/dillon-co/uniapp-web
    newTag: latest

patches:
  - target:
      kind: Deployment
      name: uniapp-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 1Gi
  - target:
      kind: Deployment
      name: uniapp-web
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
